### PR TITLE
added fix for projectName not in solution. Added ability to disable projectParsing entirely. Fixes #21

### LINKED ISSUE #21: Solution parsed multiple time when projectName is not found.
Is the source code for these two executables available?

### PR DESCRIPTION
**Pull request by Lugoues**

### CODE REVIEW

**Comment by Lugoues** [comment]
New to this gradle/groovy stuff, but this seems to solve the problem we spoke of in Issues #21

**Comment by gluck** [comment]
I was tempted to throw an error instead, do you have a use case for "not providing a project" ?
AFAICT if you use msbuild plugin in your gradle build, you're supposed to use it to build some project, and I don't see why the target project would be un-available on a build server.

Thanks !

**Comment by Lugoues** [comment]
I want to compile the entire solution with no specific project in mind (since it contains multiple output projects). On a build server, which uses clean environments each time, the gain in tracking input/output objects seems to be minimal (nonexistent?) since you will want to build everything.

File: src/main/groovy/com/ullink/Msbuild.groovy [hunk 1]
```diff
@@ -122,11 +123,15 @@ class Msbuild extends ConventionTask {
...
 
     boolean resolveProject() {
-        if (projectParsed == null) {
+        if (projectParsed == null && parseProject == true) {
             if (isSolutionBuild()) {
                 def result = parseProjectFile(getSolutionFile())
                 allProjects = result.collectEntries { [it.key, new ProjectFileParser(msbuild: this, eval: it.value)] }
                 projectParsed = allProjects[getProjectName()]
+                if (projectParsed == null) {
+                    parseProject = false
```
Comment (gluck) [inline src/main/groovy/com/ullink/Msbuild.groovy]: above method getProjects will return null in that case. As projects have been parsed and are available I think it'll be better to return the actual list, no ?

**Comment by gluck** [comment]
Sounds legit enough, plus msbuild allows to build the sln w/o specifying a project, no reason this plugin would prevent that.
Cleanest approach would be to collect inputs/outputs for every project included in that case (I guess), but this can be left for future improvement

File: src/main/groovy/com/ullink/Msbuild.groovy (hunk 1 above)
Comment (Lugoues) [inline src/main/groovy/com/ullink/Msbuild.groovy]: True. What if we have getProjects just return allProjects. If resolveProject works then allProjects will be set, if something failed it will still be null.

Comment (gluck) [inline src/main/groovy/com/ullink/Msbuild.groovy]: LGTM
